/**
 * Represents an AI-assisted edit event within a collaborative session.
 */
export interface AIEvent {
  /** Stable unique identifier for the AI event. */
  readonly id: string;
  /** Identifier of the session associated with the event. */
  readonly sessionId: string;
  /** User identifier for the actor who initiated the event. */
  readonly userId: string;
  /** Model name used to generate the event. */
  readonly model: string;
  /** Prompt sent to the model. */
  readonly prompt: string;
  /** Diff generated by the model. */
  readonly diff: string;
  /** Repository-relative files touched by the event. */
  readonly filesTouched: readonly string[];
  /** Whether the generated change was accepted. */
  readonly accepted: boolean;
  /** ISO-8601 timestamp for the event. */
  readonly timestamp: string;
}
